// <auto-generated />
using System;
using FlashFitClassLibrary.InitialData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlashFitClassLibrary.Migrations.CoreServicesApplicationDb
{
    [DbContext(typeof(CoreServicesApplicationDbContext))]
    [Migration("20230721104542_UdpateCheatmealRecordEntityagain")]
    partial class UdpateCheatmealRecordEntityagain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlashFitClassLibrary.Models.CheatmealModel", b =>
                {
                    b.Property<int>("CheatmealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheatmealId"));

                    b.Property<decimal>("CheatCalorieGain")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("CheatmealName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.HasKey("CheatmealId");

                    b.ToTable("CheatmealType");
                });

            modelBuilder.Entity("FlashFitClassLibrary.Models.CheatmealRecordModel", b =>
                {
                    b.Property<int>("CheatmealRecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheatmealRecordID"));

                    b.Property<DateTime>("CheatmealAddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CheatmealId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheatmealRecordedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheatmealUpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WeightAtMealRecordTime")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("CheatmealRecordID");

                    b.HasIndex("CheatmealId");

                    b.ToTable("CheatmealRecord");
                });

            modelBuilder.Entity("FlashFitClassLibrary.Models.WorkoutModel", b =>
                {
                    b.Property<int>("WorkoutID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkoutID"));

                    b.Property<decimal>("CaloryBurnRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkoutName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkoutType")
                        .IsRequired()
                        .HasColumnType("nvarchar(129)");

                    b.HasKey("WorkoutID");

                    b.ToTable("WorkoutType");
                });

            modelBuilder.Entity("FlashFitClassLibrary.Models.WorkoutRecordModel", b =>
                {
                    b.Property<int>("WorkoutRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkoutRecordId"));

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WeightAtCompletion")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("WorkedoutDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WorkoutRecordAddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WorkoutRecordUpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkoutTypeId")
                        .HasColumnType("int");

                    b.HasKey("WorkoutRecordId");

                    b.HasIndex("WorkoutTypeId");

                    b.ToTable("WorkoutRecord");
                });

            modelBuilder.Entity("FlashFitClassLibrary.Models.CheatmealRecordModel", b =>
                {
                    b.HasOne("FlashFitClassLibrary.Models.CheatmealModel", "Cheatmeal")
                        .WithMany()
                        .HasForeignKey("CheatmealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cheatmeal");
                });

            modelBuilder.Entity("FlashFitClassLibrary.Models.WorkoutRecordModel", b =>
                {
                    b.HasOne("FlashFitClassLibrary.Models.WorkoutModel", "WorkoutModel")
                        .WithMany()
                        .HasForeignKey("WorkoutTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutModel");
                });
#pragma warning restore 612, 618
        }
    }
}
